from pathlib import Path

bundle = Path("public/rhwp-studio/assets/index-CRsGAVvx.js")
text = bundle.read_text(encoding="utf-8")
needle = "case`exportHwpVerify`:await To,a(JSON.parse(X.exportHwpVerify()));break;default:a(void 0,`Unknown method: ${r}`)"
insert = r"""case`exportHwpVerify`:await To,a(JSON.parse(X.exportHwpVerify()));break;case`extractTextBlocks`:await To;{let e=[];let t=1;try{let e0=JSON.parse(X.doc.getDocumentInfo());t=e0.sectionCount||e0.sections?.length||1}catch{}for(let n=0;n<t;n++){let r=0;try{r=X.getParagraphCount(n)}catch{continue}for(let t=0;t<r;t++){let r=0;try{r=X.getParagraphLength(n,t)}catch{}try{let i=r?X.getTextRange(n,t,0,r):``;i&&e.push({type:`paragraph`,id:`p-${n}-${t}`,sectionIndex:n,paragraphIndex:t,length:r,text:i})}catch{}for(let r=0;r<20;r++){let i=null;try{i=X.getTableDimensions(n,t,r)}catch{}if(!i)continue;let a=Number(i.rows||i.rowCount||i.height||0)||0,o=Number(i.cols||i.colCount||i.width||0)||0,s=a*o;if(!s)continue;for(let i=0;i<s;i++){let s=0;try{s=X.getCellParagraphCount(n,t,r,i)}catch{continue}for(let c=0;c<s;c++){let s2=0;try{s2=X.getCellParagraphLength(n,t,r,i,c)}catch{}try{let l=s2?X.getTextInCell(n,t,r,i,c,0,s2):``;l&&e.push({type:`tableCell`,id:`c-${n}-${t}-${r}-${i}-${c}`,sectionIndex:n,parentParagraphIndex:t,controlIndex:r,cellIndex:i,cellParagraphIndex:c,length:s2,text:l,rows:a,cols:o})}catch{}}}}}}a(e);break}case`applyTextPatches`:await To;{let e=i?.patches||[];for(let t of e){if(t.type===`paragraph`){let e=0;try{e=X.getParagraphLength(t.sectionIndex,t.paragraphIndex)}catch{}e>0&&X.deleteText(t.sectionIndex,t.paragraphIndex,0,e);t.text&&X.insertText(t.sectionIndex,t.paragraphIndex,0,t.text)}else if(t.type===`tableCell`){let e=0;try{e=X.getCellParagraphLength(t.sectionIndex,t.parentParagraphIndex,t.controlIndex,t.cellIndex,t.cellParagraphIndex)}catch{}e>0&&X.deleteTextInCell(t.sectionIndex,t.parentParagraphIndex,t.controlIndex,t.cellIndex,t.cellParagraphIndex,0,e);t.text&&X.insertTextInCell(t.sectionIndex,t.parentParagraphIndex,t.controlIndex,t.cellIndex,t.cellParagraphIndex,0,t.text)}}a({ok:!0,count:e.length});break}default:a(void 0,`Unknown method: ${r}`)"""
if needle not in text:
    raise SystemExit("patch target not found")
text = text.replace(needle, insert, 1)
bundle.write_text(text, encoding="utf-8")
print("patched", bundle)
